config/routes.rb
Rails.application.routes.draw do
  resources :registered_applications

  devise_for :users

  get 'about' => 'welcome#about'

  root 'welcome#index'

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :registered_application, optional: true
end

app/models/registered_application.rb
class RegisteredApplication < ApplicationRecord
  belongs_to :user, optional: true

  validates :title, presence: true
  validates :url, presence: true

  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :registered_applications, dependent: :destroy
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  before_filter :set_access_control_headers
  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if registered_application.nil?
      render json: "Unregistered application", status: :unprocessable_entity
    end

    @event= registered_application.events.new(event_params)
    if @event.save
      render json: @event, status: :created
    else
      render json: {errors: @event.errors}, status: :unprocessable_entity
    end
  end

  def preflight
    head 200
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @registered_applications = RegisteredApplication.all
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
    @events = @registered_application.events.group_by(&:name)
  end

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = RegisteredApplication.new(registered_application_params)
    @registered_application.user = current_user

    if @registered_application.save
      flash[:notice] = "Registered application was saved."
      redirect_to @registered_application
    else
      flash.now[:alert] = "There was an error saving the registered application. Please try again."
      render :new
    end
  end

  def edit
    @registered_application = RegisteredApplication.find(params[:id])
  end

  def update
    @registered_application = RegisteredApplication.find(params[:id])
    @registered_application.assign_attributes(registered_application_params)

    if @registered_application.save
      flash[:notice] = "Registered application was updated."
      redirect_to @registered_application
    else
      flash.now[:alert] = "There was an error saving the application. Please try again."
      render :edit
    end
  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])

    if @registered_application.destroy
      flash[:notice] = "\"#{@registered_application.title}\" was deleted successfully."
      redirect_to registered_applications_path
    else
      flash.now[:alert] = "There was an error deleting the application."
      render :show
    end
  end

  private

  def registered_application_params
    params.require(:registered_application).permit(:title, :url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <div class="container">
      <ul class="nav nav-tabs">
        <div class="pull-right user-info">
          <% if user_signed_in? %>
            Signed in as: <strong><%= current_user.email %></strong> |
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
            <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Apps", registered_applications_path %></li>
      </ul>
      <%= yield %>
    </div>
  </body>
</html>

app/views/registered_applications/edit.html.erb
<br>
<h1>Edit Registered Application</h1>

<div class="row">
   <div class="col-md-4">
     <h3>Edit the application information below</h3>
   </div>
   <div class="col-md-8">
     <%= form_for @registered_application do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter application title/name" %>
       </div>
       <div class="form-group">
         <%= f.label :url %>
         <%= f.text_field :url, class: 'form-control', placeholder: "Enter application's URL" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-primary' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/registered_applications/index.html.erb
<div class="well">
<h1>Registered Applications</h2>
</div>


    <div class="container">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Application</th>
            <th>URL</th>
          </tr>
        </thead>

          <tbody>
              <% @registered_applications.each do |app| %>
            <tr>
              <td>
                <h4 class="media-heading">
                  <%= link_to app.title, app %>
                </h4>
              </td>
              <td>
                <h4 class="media-heading">
                  <%= app.url %>
                </h4>
              </td>
            </tr>
              <% end %>
          </tbody>
        </table>
      </div>

      <%= link_to "Register an Application", new_registered_application_path, class: 'btn btn-primary' %>

app/views/registered_applications/new.html.erb
<h1>New Application Registration</h1>

<div class="row">
  <div class="col-md-4">
    <h4>Register a new application below</h4>
  </div>
  <div class="col-md-8">
    <%= form_for @registered_application do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter application title/name"%>
      </div>

      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_area :url, class: 'form-control', placeholder: "Enter application's URL" %>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/registered_applications/show.html.erb
<br>
<div class="well col-lg-10 col-md-12 col-sm-12 col-xs-12">
  <h1 class="text-primary"><%= @registered_application.title %></h1>
  <!-- <div class="col-md-8"> -->
    <h3><%= link_to @registered_application.url %></h3>
    <h4>Registered by: <%= mail_to @registered_application.user.email %></h4>
  <!-- </div> -->
  <br>

  <div class="col-md-4">
    <%= link_to "Edit", edit_registered_application_path(@registered_application), class: 'btn btn-success' %>
    <%= link_to "Remove Application", @registered_application, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to unregister this application?'} %>
  </div>
  </div>
  <br>


    <div class="col-lg-10 col-md-12 col-sm-12 col-xs-12">
      <h3><%= @events.count %> Events</h3>
      <%= pie_chart @registered_application.events.group(:name).count %>
      <%= line_chart @registered_application.events.group_by_minute(:created_at).count %>
      <ol>
      <% @events.each do |event| %>
      <li><%= event %></li>
      <% end %>
    </ol>
    </div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<section class="bgimage">
  <div class="container-fluid">
    <div class="row">
      <div class="container-fluid">
        <h1>Blocmetrics</h1>
        <small id="tagline">a Blue Lion joint</small>
      </div>
    </div>
  </div>
</section>
<br>
<div class="text-center">
  <i class="glyphicon glyphicon-hand-right"></i>
  <%= link_to "Learn more", about_path, class: 'btn btn-primary btn-large' %>
  <i class="glyphicon glyphicon-hand-left"></i>
</div>
<br>

<!--Info section beneath banner -->

<div class="jumbotron jumbotron-fluid">
  <div class="text-center">
    <h4 class="text-primary"> Sign up for blocmetrics today! </h4>
      <%= link_to "Sign In", new_user_session_path %> or
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-danger" %>
    </p>
  </div>
</div>


<div class="row">
  <div class="col-md-4">
    <h2>Option 1</h2>
    <p>Option 1 explanation</p>
  </div>
  <div class="col-md-4">
    <h2>Option 2</h2>
    <p>Option 2 explanation</p>
  </div>
  <div class="col-md-4">
    <h2>Option 3</h2>
    <p>Option 3 explanation</p>
  </div>
</div>